In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
data = pd.read_excel("Fertility.xlsx")

In [3]:
data.head(10)

Season   Age  ChildDisease  Accident  Surgery  Fevers  Alcohol  Smoking  \
0   -0.33  0.69             0         1        1       0      0.8        0   
1   -0.33  0.94             1         0        1       0      0.8        1   
2   -0.33  0.50             1         0        0       0      1.0       -1   
3   -0.33  0.75             0         1        1       0      1.0       -1   
4   -0.33  0.67             1         1        0       0      0.8       -1   
5   -0.33  0.67             1         0        1       0      0.8        0   
6   -0.33  0.67             0         0        0      -1      0.8       -1   
7   -0.33  1.00             1         1        1       0      0.6       -1   
8    1.00  0.64             0         0        1       0      0.8       -1   
9    1.00  0.61             1         0        0       0      1.0       -1   

   sittinghours Diagnosis  
0          0.88         N  
1          0.31         O  
2          0.50         N  
3          0.38         N  
4          0.50         O  
5          0.50         N  
6          0.44         N  
7          0.38         N  
8          0.25         N  
9          0.25         N

In [4]:
X = data.drop('Diagnosis', axis=1)
y = data['Diagnosis']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [6]:
# SVM
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_pred)
svm_cm = confusion_matrix(y_test, svm_pred)

In [7]:
# Naive Bayes
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
nb_pred = nb_model.predict(X_test)
nb_accuracy = accuracy_score(y_test, nb_pred)
nb_cm = confusion_matrix(y_test, nb_pred)

In [8]:
# Decision Tree
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_pred)
dt_cm = confusion_matrix(y_test, dt_pred)

In [9]:
print("SVM Accuracy:", svm_accuracy)
print("SVM Confusion Matrix:")
print(svm_cm)
print("\nNaive Bayes Accuracy:", nb_accuracy)
print("Naive Bayes Confusion Matrix:")
print(nb_cm)
print("\nDecision Tree Accuracy:", dt_accuracy)
print("Decision Tree Confusion Matrix:")
print(dt_cm)

SVM Accuracy: 0.9
SVM Confusion Matrix:
[[27  0]
 [ 3  0]]

Naive Bayes Accuracy: 0.9333333333333333
Naive Bayes Confusion Matrix:
[[27  0]
 [ 2  1]]

Decision Tree Accuracy: 0.8
Decision Tree Confusion Matrix:
[[23  4]
 [ 2  1]]


In [15]:
X_pred = [[-1,0.67,0,0,1,0,0.6,0,0.5]]
y_pred_svm = svm_model.predict(X_pred)
print("Prediction from SVM = ", y_pred_svm)

Prediction from SVM =  ['N']


/Users/arijitbhattacharyay/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [19]:
y_pred_nb = nb_model.predict(X_pred)
print("Prediction from Naive Bayes = ", y_pred_nb)

Prediction from Naive Bayes =  ['N']


/Users/arijitbhattacharyay/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [20]:
y_pred_dtree = dt_model.predict(X_pred)
print("Prediction from Decision Tree = ", y_pred_dtree)

Prediction from Decision Tree =  ['O']


/Users/arijitbhattacharyay/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
